# Site settings
title: eBook
baseurl: "https://greglejeune.github.io/ebook"
url: "https://greglejeune.github.io/ebook/"

# Settings
markdown: kramdown
permalink: pretty

collections:
  poker:
    output: true
  servicenow:
    output: true
  ccg:
    output: true
  gdp:
    output: true
